spring:
  datasource:
    url: jdbc:mysql://47.99.68.125:3306/mall_member?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&autoReconnect=true&failOverReadOnly=false&useSSL=false