server:
  port: 8083
spring:
  application:
    name: mall-sale
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.99.68.125:3306/mall_sale?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&autoReconnect=true&failOverReadOnly=false&useSSL=false
    username: root
    password: root123456
