server:
  port: 10040
spring:
  application:
    name: mall-sale
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.99.68.125:3306/mall_sale?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&autoReconnect=true&failOverReadOnly=false&useSSL=false
    username: root
    password: root123456
  cloud:
    nacos:
      server-addr: 47.99.68.125:8848
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl